# .pre-commit-config.yaml
repos:
  # Usa i tool LOCALI invece di scaricarli
  - repo: local
    hooks:
      - id: black
        name: Black formatter
        entry: black
        language: system
        types: [python]
        require_serial: true
      
      - id: ruff
        name: Ruff linter
        entry: ruff check --fix
        language: system
        types: [python]
        require_serial: false
      
      - id: tests
        name: Run tests
        entry: pytest tests/ -v
        language: system
        pass_filenames: false
        always_run: true
      