# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff linter
        entry: ruff check --fix
        language: system
        types: [python]
        files: ^(src/|tests/)
        require_serial: false
      
      - id: ruff-format
        name: Ruff formatter
        entry: ruff format
        language: system
        types: [python]
        files: ^(src/|tests/)
        require_serial: true

      
      - id: mypy
        name: MyPy type checker
        entry: mypy
        language: system
        types: [python]
        require_serial: false
        files: ^src/
      
      - id: tests
        name: Run tests
        entry: pytest tests/ -v
        language: system
        pass_filenames: false
        always_run: true